---

- name: "Playbook: Rebuild VM"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    # - ansible.builtin.include_role: # rebuild vm
    #     name: alex.proxmox.rebuildvm
    - ansible.builtin.include_role: # configure vyos
        name: alex.truenas.configurebase

